### ISSUE TITLE
Add shortcuts for options

### ISSUE THREAD

**Issue by doktorbro** [penibelst/jekyll-compress-html#28]
The user should be able to write `all` for all the possible elements.

``` yaml
compress_html:
  clippings: all
  endings: all
```
