### ISSUE TITLE
Introduce a shortcut for all comments

### ISSUE THREAD

**Issue by penibelst** [penibelst/jekyll-compress-html#40]
The shortcut `all` speaks for itself.

```yaml
compress_html:
  comments: all
  # same
  comments: ["<!--", "-->"]
```
